            - name: github workflows queue
  # You may pin to the exact commit or the version.
  # uses: rpadaki/turnstyle@841f10bf4aca682e70903c2dd79842e3b1708a5b
  uses: rpadaki/turnstyle@v1.1
  with:
    # Number of seconds to wait in between checks for previous run completion (defaults to 60)
    poll-interval-seconds: # optional
    # Maximum number of seconds to wait before moving forward (unbound by default). Mutually exclusive with abort-after-seconds
    continue-after-seconds: # optional
    # Maximum number of seconds to wait before failing the step (unbound by default). Mutually exclusive with continue-after-seconds
    abort-after-seconds: # optional
    # Only wait on other runs from the same branch (defaults to true)
    same-branch-only: # optional
    # Total elapsed seconds within which period the action will refresh the list of current runs, if no runs were found in the first poll (0 by default, ie doesn't retry)
    initial-wait-seconds: # optional
          
